PART_BY_END = {
    '': {'VERB', 'NOUN', 'NUMR', 'GRND', 'ADVB'},
    'а': {'VERB', 'NOUN', 'ADJS', 'PRTS', 'NPRO', 'NUMR'},
    'ам': {'NPRO', 'NUMR', 'NOUN'},
    'ям': {'NOUN'},
    'ами': {'NPRO', 'NUMR', 'NOUN'},
    'ями': {'NOUN'},
    'ас': {'NPRO'},
    'ый': {'ADJF', 'PRTF'},
    'ых': {'ADJF', 'PRTF'},
    'ыми': {'ADJF', 'PRTF'},
    'ым': {'ADJF', 'PRTF'},
    'ые': {'ADJF', 'PRTF'},
    'aт': {'VERB'},
    'ят': {'VERB'},
    'ax': {'NUMR', 'NOUN'},
    'яx': {'NUMR', 'NOUN'},
    'ая': {'ADJF', 'PRTF', 'NOUN'},
    'е': {'NPRO', 'ADJF', 'NUMR', 'NOUN'},
    'ее': {'ADJF', 'PRTF'},
    'её': {'NPRO'},
    'его': {'ADJF', 'PRTF'},
    'ей': {'NPRO', 'ADJF', 'PRTF', 'NOUN'},
    'ем': {'NPRO', 'ADJF', 'PRTF', 'NOUN'},
    'еми': {'ADJF', 'PRTF'},
    'ему': {'ADJF', 'PRTF'},
    'емя': {'NUMR'},
    'яя': {'ADJF', 'PRTF'},
    'юю': {'ADJF', 'PRTF'},
    'ex': {'ADJF', 'PRTF'},
    'ею': {'NOUN', 'ADJF', 'PRTF', 'NPRO'},
    'ет': {'VERB'},
    'ёт': {'VERB'},
    'ете': {'VERB'},
    'ёте': {'VERB'},
    'ёх': {'NUMR'},
    'ешь': {'VERB'},
    'ёшь': {'VERB'},
    'и': {'NPRO', 'ADJS', 'PRTS', 'NOUN', 'VERB'},
    'ие': {'ADJF', 'PRTF', 'NOUN'},
    'ий': {'ADJF', 'PRTF', 'NOUN'},
    # 'ий': {'PRTF'},
    'им': {'NOUN', 'ADJF', 'PRTF', 'NUMR', 'NPRO', 'VERB'},
    'ими': {'NOUN', 'ADJF', 'PRTF', 'NPRO'},
    'ит': {'VERB'},
    'ите': {'VERB'},
    'их': {'NOUN', 'ADJF', 'PRTF', 'NUMR', 'NPRO'},
    'ишь': {'VERB'},
    'ию': {'NOUN'},
    'м': {'VERB'},
    'ми': {'NOUN'},
    'мя': {'NUMR'},
    'о': {'VERB', 'NOUN', 'ADJS', 'NPRO', 'NUMR', 'ADJF', 'PRTF'},
    'ов': {'NOUN'},
    'ого': {'NOUN', 'ADJF', 'PRTF', 'NPRO'}, 'ое': {'ADJF', 'PRTF', 'NOUN'},
    'оё': {'ADJF', 'PRTF'},
    'ой': {'NPRO', 'ADJF', 'PRTF', 'NOUN'},
    'ом': {'VERB', 'NOUN', 'NPRO', 'NUMR', 'ADJF', 'PRTF'},
    'ому': {'NOUN', 'ADJF', 'PRTF', 'NPRO'},
    'ою': {'NPRO', 'ADJF', 'PRTF', 'NOUN'},
    'cт': {'VERB'},
    'ть': {'VERB'},
    'ти': {'VERB'},
    'у': {'VERB', 'ADJF', 'PRTF', 'NOUN'},
    'ум': {'NUMR'},
    'умя': {'NUMR'},
    'ут': {'VERB'},
    'ют': {'VERB'},
    'ух': {'NUMR'},
    'ую': {'ADJF', 'PRTF', 'NOUN'},
    'шь': {'VERB'},
    'я': {'NOUN', 'VERB'},
    'ю': {'NOUN', 'VERB'},

}

PAST_TENSE_VERB_ENDINGS = {'а', 'о', 'и'}
